(function () {

/* Imports */
var Meteor = Package.meteor.Meteor;
var global = Package.meteor.global;
var meteorEnv = Package.meteor.meteorEnv;

/* Package-scope variables */
var _bootstrapGetAsset, _bootstrapGetJsList;

(function(){

///////////////////////////////////////////////////////////////////////////////////////
//                                                                                   //
// packages/huttonr_bootstrap3-assets/serve.js                                       //
//                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////
                                                                                     //
_bootstrapGetAsset = function (path) {
  return Assets.getText(path);
};

_bootstrapGetJsList = function () {
  return jsAssetNames.slice();
}

// Do not edit this list, it is generated by the bash script, run the script instead
var jsAssetNames = ['affix.js','alert.js','button.js','carousel.js','collapse.js','dropdown.js','modal.js','popover.js','scrollspy.js','tab.js','tooltip.js','transition.js'];

///////////////////////////////////////////////////////////////////////////////////////

}).call(this);


/* Exports */
if (typeof Package === 'undefined') Package = {};
(function (pkg, symbols) {
  for (var s in symbols)
    (s in pkg) || (pkg[s] = symbols[s]);
})(Package['huttonr:bootstrap3-assets'] = {}, {
  _bootstrapGetAsset: _bootstrapGetAsset,
  _bootstrapGetJsList: _bootstrapGetJsList
});

})();
